### ISSUE TITLE
Would you like develope a version of golang?

### ISSUE THREAD

**Issue by epoll486** [oracle/weblogic-monitoring-exporter#1]

**Comment by russgold** [comment]
Could you say more about this? What is the goal, here? What problem are you looking to solve?

**Comment by russgold** [comment]
Please note that there are two tools, here. The Configuration coordinator is standalone, and implemented in Go. The Weblogic Monitoring Exporter is a servlet installed with the WLS, and is therefore implemented in Java. This allows it to take advantage of WLS handling of requests, and simplifies detection of new instances by Prometheus.

**Comment by russgold** [comment]
With no responses, I am closing this.
