### ISSUE TITLE
Does this work with WebLogic Server Version: 10.3.6.0

### ISSUE THREAD

**Issue by rbalabad** [oracle/weblogic-monitoring-exporter#104]
Hi,
I am getting "Error 404--Not Found" while accessing <biserver>/wls-exporter/metrics even after deploying wls-exporter as web application via weblogic. Is this supported on OBIEE 11g?

Appreciate your feedback.

Thanks,
Raj

**Comment by rbalabad** [comment]
I am using WebLogic Server Version: 10.3.6.0 which comes as part of OBIEE 11g installation.

**Comment by markxnelson** [comment]
As stated in the main README, this is supported on WebLogic Server 12.2.1 and later.  It depends on WebLogic Server features that were not present in earlier releases.
