### ISSUE TITLE
Pulling DMS Metrics

### ISSUE THREAD

**Issue by ahinh43** [oracle/weblogic-monitoring-exporter#12]
Hi,

I'm currently running Oracle WebLogic Server 12.2.1.3.0 and I was looking to export the DMS Metrics with the exporter, but I'm a little lost on what metric I would be querying from to get the results I want from the MBeans portion of the metrics page.

![image](https://user-images.githubusercontent.com/14356001/50352199-23350580-050a-11e9-941c-8be9c52ea0ee.png)

For example, I'd like to get the metrics from the OAM_Authn exported but I'm unsure where in the Mbean list I would find the same data in.
![image](https://user-images.githubusercontent.com/14356001/50352256-55defe00-050a-11e9-8fda-913a08c5fc13.png)

Would I have to configure something on the WebLogic Server side to pull the same metrics and allow it to be exported with the exporter? Or is it present in the database somewhere that I may be accidentally skipping over?

Thank you!

**Comment by LorenKonkus** [comment]
Since the Monitoring Exporter leverages WebLogic Server RESTful Management Services, it is limited to those metrics surfaced via WLS mbeans and rest. Many of the DMS metrics are outside  of that  scope. including those provided by OAM.
