### ISSUE TITLE
Including host name

### ISSUE THREAD

**Issue by senthil13** [oracle/weblogic-monitoring-exporter#122]
Hi Team,
How to get the host name also in the metrics?

`wls_jvm_uptime` it provides the domain name and the server name but not the host name, Please direct me where from I can include the host name.

`wls_jvm_uptime{domain="demo_domain",server="managedserver_1"} 338725691`

Expected

`wls_jvm_uptime{domain="demo_domain",server="managedserver_1",host="server1.abc.com"} 338725691`

**Comment by ddsharpe** [comment]
A given managed server (normally) only exists on a single host.  Only through server migration would you see the same managed server on two hosts.  The uptime would only have a value on ONE of those.  The host that a given managed server is running on might be available somewhere else, but will not be available on wls_jvm_uptime.
