### ISSUE TITLE
How to run WLS- exporter.war

### ISSUE THREAD

**Issue by FreshZhang** [oracle/weblogic-monitoring-exporter#137]
How to run WLS- exporter.war？I run it through java - jar WLS- exporter.war, but I report an error:no main manifest attribute, in wls-exporter.war,How to solve this problem？

**Comment by russgold** [comment]
A WAR is a Web Application ARchive. You have to deploy it to a WebLogic Server instance. I am currently working on a standalone program that can do what you suggest, although it's user interface will be different.

**Comment by AtakanColak** [comment]
@FreshZhang see relevant [doc](https://docs.oracle.com/cd/E19424-01/820-4807/war-weblogic/index.html)
