### ISSUE TITLE
Cannot access any metrics when WebLogic domain administration port is configured

### ISSUE THREAD

**Issue by serafeimk** [oracle/weblogic-monitoring-exporter#138]
Steps to reproduce: 
- setup a WebLogic domain with Administration port configured 
- deploy wls-exporter.war into one managed server with embedded yaml file. Its head section contains only the _metricsNameSnakeCase: true_ directive which is followed by the queries section.
- access /wls-exporter/metrics page via a GET request. HTTP 403 error code is returned along with the text response "Not authorized". There is no prompt for basic authentication.

**Comment by russgold** [comment]
That version of the exporter are you using? Older versions did not support https

**Comment by serafeimk** [comment]
We are using the 1.3.0 version of exporter under WebLogic 12.2.1.3. Even by invoking the URL /wls-exporter/metrics page using HTTP/s returns 403 and still no prompt for authentication.

**Comment by russgold** [comment]
What do you see at /wls-exporter/messages ?

**Comment by serafeimk** [comment]
Just the `"Not authorized"` message. Are there are debugging options that we can leverage to increase logging ?

**Comment by lennyphan** [comment]
can you try setting the wls-exporter application in 'admin' state and then see if you can access it on the admin port?  Is there a reason you want to access the exporter metrics via admin port and not through the http/https ports?

**Comment by serafeimk** [comment]
Lenny,

many thanks for the response. After placing the app into admin state and accessing the URL /wls-exporter/metrics via the administration channel, we are constantly requested for providing the basic authentication credentials. Even though we submit correct credentials for the WLS domain administrator account, we are prompted again and again.

**Comment by lennyphan** [comment]
That's very strange.  Lets try and enable security debugging for authentication to see if it provides any information on why it's not accepting the credentials.  You can either use system property on the managed server:

-Dweblogic.debug.DebugSecurityAtn=true

or 

in the admin server console:

1. Go to Servers > server_Instance.
2. Select WebLogic > Security > atn > DebugSecurityAtn
3. Click the Enable button.

**Comment by serafeimk** [comment]
The server log is attached after enabling the debugging flag. Still not sure what is going wrong.
[debugatn.log](https://github.com/oracle/weblogic-monitoring-exporter/files/5994657/debugatn.log)

**Comment by lennyphan** [comment]
Is user 'jenkins' (with password) the credentials used when submitting when prompted?  The log doesn't show anything that helps pinpoint what is going wrong.  Are you able to access the Admin Server console and login through the administration port?

**Comment by serafeimk** [comment]
That's correct. We use account 'jenkins' for accessing Admin Server console (in administration port) Additionally, we tried to access the /wls-exporter/metrics URL using the 'weblogic' account but no effect: the basic authentication window keeps popping up.

**Comment by russgold** [comment]
So you have two ports open now? The admin port and the SSL port? And you are querying the exporter on the SSL port?

If so, please try this. Add `restPort` to your configuration and have it point to the admin port. Then try to access the exporter on the SSL port.

**Comment by serafeimk** [comment]
After setting the 'restPort' pointing to the managed server administration port and accessing the metrics URL in the SSL port, we still cannot access the metrics, as the basic authentication popup repeatively shows up, after submitting correct credentials.

**Comment by lmpampaletakis** [comment]
Same issue here

**Comment by russgold** [comment]
> Same issue here

Impampaletakis, which issue are you having? I'm hearing two different ones, now.

**Comment by lmpampaletakis** [comment]
When the admin port is enabled to the weblogic domain, trying to access /metrics is not feasible, using the SSL port of the managed server, The error I get is HTTP 403 Forbidden.

**Comment by lmpampaletakis** [comment]
After upgrating the restPort to my admin port, through the configuration, I am constantly getting a popoup to provide credentials. Even though I give right username and password, the pop up is never dispappeared.

**Comment by russgold** [comment]
OK, that's what serafeimk is seeing as well, and which I have not been able to duplicate. I'm going to have to try to figure out what is going on there.

**Comment by russgold** [comment]
Would you please try this from the command line:
```
curl --user <user>:<password> \
>        --insecure\
>        -d '{"links":[], "fields":[]}' \
>        -H "Content-Type: application/json" \
>        -H "X-Requested-By: exporter" \
>        -X POST https://<host>:<admin-port>/management/weblogic/latest/serverRuntime/search
```

making the appropriate substitutions for <user> <password> <host> and <admin-port>

For me, this returns the string "{}"

If you are getting a 401, that would indicate a problem with your user/password.

**Comment by serafeimk** [comment]
I can confirm that the curl call returns "{}". By removing the ``--insecure`` flag we get a error about :

``curl: (60) SSL certificate problem: self signed certificate in certificate chain``

but non sure if that is relative to our issue.

**Comment by lmpampaletakis** [comment]
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    27    0     2  100    25      0      8  0:00:03  0:00:03 --:--:--     8{}

**Comment by serafeimk** [comment]
It is confirmed that building from latest source, we are able to pull metrics, with basic authentication prompted only once. Many thanks for the great support ! Eagerly awaiting the next release.

Note: we had to skip tests during ``mvn install`` because of a failure in the ``com.oracle.wls.exporter.MultipartContentParserTest.parseFormFields`` method

**Comment by mriccell** [comment]
This issue has been addressed
