### ISSUE TITLE
Grafana dasboard

### ISSUE THREAD

**Issue by piotrekbed** [oracle/weblogic-monitoring-exporter#143]
I successfully deployed metrics' exporter in my weblogic server. I connected it with my prometheus but I can't find working grafana dashboards for weblogic. 
I tried to use  this "weblogic-monitoring-exporter/samples/kubernetes/end2end/grafana/dashboard.json" but metics in expresion doesn't exist.
Is there any working example of dashboard?

**Comment by xiancao** [comment]
There is a blog you can take a look.
https://blogs.oracle.com/weblogicserver/end-to-end-example-of-monitoring-weblogic-server-with-grafana-dashboards-on-the-oci-container-engine-for-kubernetes

**Comment by russgold** [comment]
There are also samples in the project, such as https://github.com/oracle/weblogic-monitoring-exporter/tree/master/samples/kubernetes/end2end/grafana

**Comment by piotrekbed** [comment]
I tried to use this dashboard, but there are queries about metrics like:
`wls_jvm_uptime
wls_jvm_heap_free_percent
wls_webapp_config_deployment_state
wls_jmsruntime_connections_current_count`
etc.
And my exporter returns the metrics:
`jvm_heap_free_percent
webapp_config_deployment_state
webapp_config_open_sessions_high_count
weblogic_servlet_execution_time_average
weblogic_servlet_execution_time_average
weblogic_servlet_invocation_total_count`

I did everything according to the instructions in read. 
Do I have to change the prefixes manually or is there a dashboard prepared for the version from the example configuration?

**Comment by marinakog** [comment]
EndToEnd sample use this config : https://github.com/oracle/weblogic-monitoring-exporter/blob/master/samples/kubernetes/end2end/dashboard/exporter-config.yaml, you need to build wls-exporter.war using that one, looks like your configuration is different . The provided grafana dashboard is matching that configuration. If you want something else to use you can just modify that dashboard to apply your values for metrics.

**Comment by piotrekbed** [comment]
Thank you, I got some data in my Grafana, but there are inaccuracies in metrics labels e.g.
In prometheus I have: 
`wls_server_activation_time{instance="YYYYY", job="wls_exporter", location="XXXXXXXX"}`
In Grafana the same metric has different labels:
`wls_server_activation_time{weblogic_domainUID="$domainName", weblogic_clusterName="$clusterName",weblogic_serverName="$serverName"}`
Is there any chance to upgrade example dashboard with current metrics' label?

**Comment by ipapakri** [comment]
I had the same problem as you. The simplest thing you can do is to add the missing info by hand to prometheus. 
In the kubernetes examples this is handled automatically via scripts during the setup.
Have a look at my comment here https://github.com/oracle/weblogic-monitoring-exporter/issues/89#issuecomment-820364379

**Comment by mriccell** [comment]
Closed this issue has been answered
