### ISSUE TITLE
Unable to get other metrics from serverRuntimeMBean

### ISSUE THREAD

**Issue by wisdom49** [oracle/weblogic-monitoring-exporter#149]
Hi Sir/Madam,
    I am using the wls-exporter.war (2.0) with the [configuration file](https://github.com/oracle/weblogic-monitoring-exporter/blob/master/samples/kubernetes/end2end/dashboard/exporter-config.yaml) to export metrics from my test environment. Unfortunately, I can see only four metrics scraped from serverRuntime. 
    
Here is the example:
wls_server_activation_time{domain="base_domain",server="ms1"} 1618894951147 wls_server_admin_server_listen_port{domain="base_domain",server="ms1"} 7001 wls_server_open_sockets_current_count{domain="base_domain",server="ms1"} 6 wls_server_state_val{domain="base_domain",server="ms1"} 2

However, I can see all the metrics through the Restful API
http://hostname:portNumber/management/weblogic/latest/serverRuntime

`   "middlewareHome": "\/u01\/app\/oracle\/fmw\/wls12.2.1.4",
    "listenPortEnabled": true,
    "weblogicHome": "\/u01\/app\/oracle\/fmw\/wls12.2.1.4\/wlserver",
    "adminServer": false,
    "SSLListenPortEnabled": true,
    "state": "RUNNING",
    "activationTime": 1618894951147,
    "defaultURL": "t3:\/\/192.168.144.134:7003",
    "adminServerListenPort": 7001,
    "currentMachine": "machine1",`

    
Is there any wrong with the exporter configuration file or any extra step that I might have missed?
Thank you!!

**Comment by russgold** [comment]
That's just a sample; it is not intended to be the configuration you actually use. You need to create a configuration, based on the mbeans that you actually want.

**Comment by wisdom49** [comment]
Dear Sir,
   Based on the description on README, specifying specific values are meant to get the values of specified MBean attributes.

![image](https://user-images.githubusercontent.com/24885621/115491385-7104d880-a292-11eb-8f20-5781a43cd263.png)

 While I defined some attributes of serverRuntimeMBean to scrape, e.g. "currentMachine"

![image](https://user-images.githubusercontent.com/24885621/115492835-2df83480-a295-11eb-9006-5d998f77d6c7.png)

I didn't get the expected result.
![image](https://user-images.githubusercontent.com/24885621/115492257-0c4a7d80-a294-11eb-9e6f-ec906a698df6.png)

If I remove the prefix and values from the configuration file, nothing I can get from serverRuntimeMBean.
Is there any problem with my configuration file for scrapping metrics?

**Comment by russgold** [comment]
The only metrics available via the exporter are those suitable for Prometheus: those with numeric values. String-valued metrics are not supported.

**Comment by wisdom49** [comment]
Hello Russgold,
    Thanks for your reply to the question.

**Comment by mriccell** [comment]
Closing since question has been answered
