### ISSUE TITLE
Get data from all managed servers

### ISSUE THREAD

**Issue by luckass1** [oracle/weblogic-monitoring-exporter#159]
First thank you!

I would like to know if it is possible to monitor all servers from http://192.168.0.104:7001/management/weblogic/latest/domainRuntime

With just one query I can get data from all managed servers through AdminServer without having to install the exporter on all of them?

**Comment by augeivv** [comment]
@luckass1 How do you solved it?

**Comment by 162783882** [comment]
@luckass1 .. How do you solved it?
