### ISSUE TITLE
How to use coordinator? 

### ISSUE THREAD

**Issue by luckass1** [oracle/weblogic-monitoring-exporter#160]
How to use coordinator? I did the docker configuration and managed to raise the service in 8999.

I'm using the command to send configs...

curl -X PUT -d @config01 http://192.168.0.103:8999

{
    "timestamp": 14567899,
    "configuration":
        "host: 192.168.0.103
         port: 7001
         query_sync:
           url: http://192.168.0.103:8999/
           refreshInterval: 10
        metricsNameSnakeCase: true
        queries:
        - applicationRuntimes:
          key: name
          keyName: app
          componentRuntimes:
            type: WebAppComponentRuntime
            prefix: webapp_config_
            key: name
            values: [openSessionsCurrentCount, openSessionsHighCount]
            servlets:
              prefix: weblogic_servlet_
              key: servletName"
}

But the configuration brings down the exporters.

![image](https://user-images.githubusercontent.com/3300393/139164087-33e1da26-b553-4d9c-b7ca-d6e1844209de.png)

![image](https://user-images.githubusercontent.com/3300393/139164119-782396f1-0f3d-4d6e-8b8b-d3a1c86fc73b.png)

I noticed that the configuration overwrites the configuration file by a JSON that is not indented correctly. How can I solve this?

**Comment by tbarnes-us** [comment]
@luckass1: I'm assuming that this issue has been addressed. If not, feel free to reopen this issue, or, better yet, you're welcome to continue discussion on the public "weblogic operator" slack channel (which also can be used for exporter issues) -- https://oracle.github.io/weblogic-kubernetes-operator/userguide/introduction/get-help/ .
