### ISSUE TITLE
Able to collect GC metrics same as JMX

### ISSUE THREAD

**Issue by Sarkie** [oracle/weblogic-monitoring-exporter#167]
Basically the ones from here:
https://gist.github.com/huynhbaoan/1bb4cd87313f56bc63cc4e19ce5c3ec7

Be able to monitor these as to know if we have GC issues

**Comment by russgold** [comment]
The exporter can only access metrics available via the REST query API. See https://docs.oracle.com/middleware/12213/wls/WLRUR/overview.htm#WLRUR118.

Some of the items you want are mentioned in the sample configurations.

**Comment by Sarkie** [comment]
How do I request them to be added? @russgold 

As this is meant to be a replacement for OEM but it doesn't have the same amount of data
