### ISSUE TITLE
Prometheus is not able to parse floating point metrics when WebLogic uses a non english Locale

### ISSUE THREAD

**Issue by echocharlie125** [oracle/weblogic-monitoring-exporter#17]
Floating point metrics expected by Prometheus must use the dot '.' as decimal separator. If WebLogic uses a regional setting which defines another decimal separator it will not work. For instance french uses a comma.
To reproduce the issue start the WebLogic JVM with these settings : 
-Duser.country=FR -Duser.language=fr

**Comment by russgold** [comment]
Fixed by commit 1908af03a3ad454 "Use US locale to encode performance metrics"
