### ISSUE TITLE
Docker sidecar persistence

### ISSUE THREAD

**Issue by dsuded** [oracle/weblogic-monitoring-exporter#171]
Hello,

I have deployed weblogic-monitoring-exporter in Docker, using image container-registry.oracle.com/middleware/weblogic-monitoring-exporter.2.0.4. Everything works OK, except when I restart (not remove) container all metrics at /metrics are lost and I need to reload them using curl command.
Is this intended, as I would like to monitor WebLogic domains that are not in Kubernetes but on bare metal, and installing exporter as an WebLogic app is not an option for me.

**Comment by russgold** [comment]
How are you installing the exporter and restarting the container? I presume that you are not using the operator, here? That's the primary use case for the sidecar.

**Comment by dsuded** [comment]
Thank you for explaining. I have edited start_exporter.sh script and added curl command at the end, so at every container start it loads metrics.
