### ISSUE TITLE
Missing datasource State metric

### ISSUE THREAD

**Issue by jlmolina-oracle** [oracle/weblogic-monitoring-exporter#184]
We need to be able to expose the "State" of a given datasource in a managed server.
As the WebLogic MBean fields that were string types were skipped by default since Prometheus was unable to support those types, currently the State is not exposed.
As suggested by @ddsharpe , is it possible to create an exception for this field ? 
The type is just an enumeration that could be translated to an integer that Prometheus would support, and from there we can interpret it correctly. 
Thanks !!

**Comment by ddsharpe** [comment]
Please be as specific as possible.  I believe that you are after the `State` attribute from `JDBCDataSourceRuntime`.  State= (Running, Suspended, Stopped, Overloaded ...).  Correct?

**Comment by jlmolina-oracle** [comment]
> t you are after the `State` attribute from `JDBCDataSourceRuntime`. State= (Running, Suspended, Stopped, Overloaded ...). Correct?

Correct !!

**Comment by jlmolina-oracle** [comment]
Do we have any news about this issue ?

**Comment by russgold** [comment]
Please try branch `string_metrics`.

**Comment by jlmolina-oracle** [comment]
Changes in branch string_metrics are correctly handling the request in this issue, not only for the "state" metric in JDBCDataSourceRuntimeMBeans , but for any string typed metric listed in "stringValues:" , which is correctly cathegorized with the values specified. 
Hence this issue can be closed
