### ISSUE TITLE
how can i get jdbc pool metric

### ISSUE THREAD

**Issue by haha-zwx** [oracle/weblogic-monitoring-exporter#20]

**Comment by russgold** [comment]
Can you find the value you want in the mbean reference? https://docs.oracle.com/middleware/1212/wls/WLMBR/core/index.html

**Comment by haha-zwx** [comment]
> Can you find the value you want in the mbean reference? https://docs.oracle.com/middleware/1212/wls/WLMBR/core/index.html

yes I can , and I mkae a demo , but I can not get the  metric  
for example: 
JDBCServiceRuntimeMBean

config.yml:
metricsNameSnakeCase: true
queries:
- applicationRuntimes:
    key: name
    keyName: app
    componentRuntimes:
      prefix: webapp_config_
      key: name
      servlets:
        prefix: weblogic_servlet_
        key: servletName

- applicationRuntimes:
    key: name
    workManagerRuntimes:
      prefix: workmanager_
      key: applicationName
      
- JVMRuntime:
    key: name
    prefix: jvm_

- JDBCServiceRuntime:
    key: name
    prefix: jdbc_

- JMSRuntime:
    key: name
    prefix: jms_


but  i  can not get metric  start by  jdbc_     
can you hele me ?  thanks!

**Comment by russgold** [comment]
What are you getting from JDBCServiceRuntime, and what field are you looking for? I see no field named "start"

**Comment by haha-zwx** [comment]
> What are you getting from JDBCServiceRuntime, and what field are you looking for? I see no field named "start"

sorry, my english is not good , i want get metric prefix "jdbc_"  
,such as ActiveConnectionsAverageCount,ActiveConnectionsCurrentCount ... 
```
- JDBCServiceRuntime:
    key: name
    prefix: jdbc_
```
like this , i can not get metric prefix "jdbc_"   , how can i get ?

**Comment by russgold** [comment]
That should work; what are you actually getting for those metrics?

**Comment by rauldiego** [comment]
I meet the same problem， how can I get jdbc metrics， waiting

**Comment by russgold** [comment]
The metrics are actually one level down. Try:

```
- JDBCServiceRuntime:
    JDBCDataSourceRuntimeMBeans:
      prefix: jdbc_
      key: name
```
