### ISSUE TITLE
Exporter is overwriting default locale

### ISSUE THREAD

**Issue by davtorrin** [oracle/weblogic-monitoring-exporter#213]
Exporter is overriding the JVM default locale to US and running applications require ES. 
ExporterCall does "Locale.setDefault(Locale.US)" and MetricsStream.printPerformanceMetrics already print metrics in US format. 

I'm not sure if exporter needs to modify the default locale, but this may cause an issue in a production environment.

**Comment by russgold** [comment]
Thanks; as far as I can tell, we do not actually need that line, and I am removing it in a pending commit.

**Comment by russgold** [comment]
The fix is now in main and will be in the next release
