### ISSUE TITLE
Fix for Issue #214 re-introduce issue #16

### ISSUE THREAD

**Issue by mingxhu** [oracle/weblogic-monitoring-exporter#218]
With Ver [2.1.0](https://github.com/oracle/weblogic-monitoring-exporter/releases/tag/v2.1.0) prometheus fails when WebLogic runs on Windows platform with https://github.com/oracle/weblogic-monitoring-exporter/issues/16, but Ver [2.0.7](https://github.com/oracle/weblogic-monitoring-exporter/releases/tag/v2.0.7) works properly. From link https://github.com/oracle/weblogic-monitoring-exporter/commit/b72a1f2cdeaf24557e686d907829cc7bef3e27f2 the change for https://github.com/oracle/weblogic-monitoring-exporter/issues/214

```
    void printMetric(String name, Object value) {
 -       print(name + " " + value + '\n');
 +       print(name + " " + value + System.lineSeparator());
        scrapeCount++;
    }
```

Which in fact reverts the fixed for https://github.com/oracle/weblogic-monitoring-exporter/issues/16

**Comment by russgold** [comment]
To satisfy other requirements, I have re-implemented this in a different way. Could you please try the 'issue_218' branch?

**Comment by mingxhu** [comment]
Tested with build from 'issue_218' branch, it works, thanks Russell!
