### ISSUE TITLE
Not authorized

### ISSUE THREAD

**Issue by wbustraan** [oracle/weblogic-monitoring-exporter#22]
When trying to test the metrics using Postman, I get 403 "Not authorized" response. In the README, I see that this passes through the authentication/authorization through to the "WLS RESTful Management Interface", however, using the same Basic auth credentials, I can submit requests to the RESTful Management Interface endpoints with no problems.

It seems I get the same "Not authorized" response even if I omit the Basic auth header. Looking at the code, it seems I should be getting a 401 "Authentication required" response in the absence of a auth header.

**Comment by russgold** [comment]
Are you able to make a reproducer for this? That is, a set of specific instructions that somebody else could follow to make it happen? We know this works, so it is likely to be your setup. If not, you may have identified an unsupported use case.

**Comment by wbustraan** [comment]
Well, I haven't modified the code in any way, so it could very well be the setup. However, this is this first time we've done anything related to the "RESTful Management Interface", so I assume that we have a stock standard configuration. From the message, it would seem like the user account does not have the appropriate role(s), but I would assume, if that was the case, that I would be unable to access RESTful Management Interface services as well. That works, whereas the exporter does not.  I've also tried with the master weblogic user, but that has the same result.

I've been looking through the Weblogic documentation to see if there is some setting in the Admin console that could alter how the RESTful services work, but I can find nothing other than the switch to turn it on, "Enable RESTful Management Services", which is checked on the domain being tested.

Are there any other settings I'm missing?

**Comment by russgold** [comment]
The exporter actually uses the credentials you give it to contact the REST API, which is why I am surprised, and looking for a way to reproduce this. I wonder if there is a problem in the handshake between the exporter and Postman. I have only tried it from a browser and Prometheus.

**Comment by wbustraan** [comment]
The fact that you are able to test it in a browser is a clue. I assume that, when you go to the URL with an incognito window, it prompts you for a Basic auth username and password? It doesn't do that for me, which is why I tried Postman; in order to add the Basic auth header to the initial request.

**Comment by russgold** [comment]
Odd that it isn't prompting you. Can you try accessing it from curl? Let's get really basic here, just in case Postman is doing something hidden.

**Comment by wbustraan** [comment]
Closing this, since I am moving to a different job position and won't be working on this any longer.
