### ISSUE TITLE
Histogram metrics ?

### ISSUE THREAD

**Issue by arduinepo** [oracle/weblogic-monitoring-exporter#241]
Hi,

Are there any metrics available as histograms please ? I would like to get easily some stats like the total number of values above an upper threshold over time, for metrics like heap percent and CPU.
If not, are there projects of exporting histograms in a near future ?

Thank you very much - and please excuse my somewhat innaccurate English, French IT companies are not the most ENglish-friendly environment.

Best,
Pat

**Comment by ddsharpe** [comment]
@arduinepo - You would not say such things about your English if you saw my French.
This exporter provides the raw data at an instant in time in a format consumable by applications like Prometheus.  Using a combination of Prometheus to collect this data over time, and Grafana to create the dashboard(s) and histograms should give you the solution you seek.  This blog might not be a perfect match for what you seek, but you should read the blog by Marina found here: https://blogs.oracle.com/weblogicserver/post/end-to-end-example-of-monitoring-weblogic-server-with-grafana-dashboards-on-the-oci-container-engine-for-kubernetes

**Comment by arduinepo** [comment]
> @arduinepo - You would not say such things about your English if you saw my French. This exporter provides the raw data at an instant in time in a format consumable by applications like Prometheus. Using a combination of Prometheus to collect this data over time, and Grafana to create the dashboard(s) and histograms should give you the solution you seek. This blog might not be a perfect match for what you seek, but you should read the blog by Marina found here: https://blogs.oracle.com/weblogicserver/post/end-to-end-example-of-monitoring-weblogic-server-with-grafana-dashboards-on-the-oci-container-engine-for-kubernetes

Thanks for the tip : I tried indeed the histogram viz, but it is not as conclusive and efficient as simpler viz displaying results of requests based on histogram metrics, like those of mtail...
