### ISSUE TITLE
Unable to load a configuration

### ISSUE THREAD

**Issue by rsiebeling** [oracle/weblogic-monitoring-exporter#25]
Hi,

I have deployed and started the weblogic monitoring exporter and see the start page but whenever I try to load a configuration it says 

10.5.1 500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

It doesn't matter what I do... do you what the problem is / can you please help?

thanks in advance,
Richard
rsiebeling@gmail.com

**Comment by russgold** [comment]
I've never seen that. Can you tell me more? How are you trying to load the configuration? Did you define an initial one as part of your WAR?

**Comment by rsiebeling** [comment]
Hi, no I've just used the initial configuration. 
I have to say I'm on a Windows 2012 R2 server and want to use the weblogic monitoring to monitor our Oracle BI system (which is fairly standard installation on one node).

I've built the war file using the instructions (mvn install, cd webapp, mvn package) without any parameters. Would it be better to use a configuration file?

Then I've deployed the war file using the Weblogic Administration Console as part of the bi_server1 cluster (see screenshot). I've also tried deploying it on all servers (checked all the boxes) but that didn't help. 

After deployed I'm able to access the starting screen on port weblogic server:9502/wls-exporter.
But when I upload a configuration file I get the internal error message.

When looking at the metrics endpoint I see that there aren't any metrics configured, the log endpoint says no errors reported and when accessing the configure endpoint directly using the url I get the message "HTTP method GET is not supported by this URL".

Hope you can help, maybe I'm doing something basic wrong (I'm not that experienced with Weblogic). But it looks alright since I'm able to access the starting screen.

Thanks for your help,
Richard

**Comment by rsiebeling** [comment]
and here's the screenshot of the targets 

<img width="207" alt="wls_exporter_targets" src="https://user-images.githubusercontent.com/3526846/58209242-f10d1700-7ce6-11e9-995f-4a120d454788.png">

**Comment by russgold** [comment]
My fault. I have just introduced a NullPointerException today, apparently. Fixing it now. Thanks for the heads up.

**Comment by rsiebeling** [comment]
ah thanks, I was thinking I did something wrong. 
I'm glad that I was able to help you :-)

**Comment by russgold** [comment]
It should be fixed now. Please let me know.

**Comment by rsiebeling** [comment]
It's working now, thanks!
