### ISSUE TITLE
Exporter version responded is not correct for FMW environments 

### ISSUE THREAD

**Issue by jlmolina-oracle** [oracle/weblogic-monitoring-exporter#256]
After deploying 2.1.1 ... we can see a "small" difference in the exporter_version metric responded 

**WLS plain envs show**
exporter_version{instance="host:7001",version="v2.1.1"} 1

**FMW based envs show**
exporter_version{instance="host:7001",version="20050516"} 1

This is also seen in the first title when accessing http://host:port/wls-exporter

==> Oracle WebLogic Monitoring Exporter *20050516.*

**Comment by russgold** [comment]
The exporter version is written as the property _version_ in a file called _version.properties_. In the web app, it is obviously seeing a conflict with another property file, so we need to rename both of them.

**Comment by russgold** [comment]
This should be corrected in the latest release.
