### ISSUE TITLE
disable credential check when accessing its metrics

### ISSUE THREAD

**Issue by lilyhe123** [oracle/weblogic-monitoring-exporter#26]
This can make the metrics seamlessly scraped by Prometheus with the common 'kubernetes_sd_config'. Otherwise when a new wls domain is running, the Prometheus configuration need to be updated with this new domain's credential to allow Prometheus scrape its metrics. On the other hand, the exported metrics is read-only and no critical information in it, so no need to protect it with an admin credential.

**Comment by russgold** [comment]
The original requirements for this tool insisted that Oracle standards mandated password protection even to read the metrics. It was not an arbitrary choice.

**Comment by russgold** [comment]
Now that we're discussing it, it seems that the basic issue is access to the REST API, which is how the exporter does its data retrieval - and that currently requires a password. So there has to be at least one username/password authentication before the exporter can function.

**Comment by russgold** [comment]
What, exactly, is the use case. Why would an existing Prometheus configuration need not to change to deal with a new wls domain?

It occurs to me that there is an alternative. We currently use a step to install the configuration into the WAR. In theory, we could also install a username/password there, which would then allow metrics to be accessed without Prometheus needing to specify the password. Would that work?

**Comment by markxnelson** [comment]
Unless Derek/Ryan/Tom want to override me - this issue should be closed as "will not do"

**Comment by TheFrogPad** [comment]
Please do not deploy an application with a username/password used to access the REST APIs.

**Comment by lilyhe123** [comment]
Auto service discovery is an attracting feature of Prometheus. Services can come and go while Prometheus can auto detect new services and scrape metrics from them. So I thought if it's easy we can leverage this feature. But seems there is no easy way since REST API invocation requires authentication.  So maybe doesn't worth it.

**Comment by russgold** [comment]
Yes, and the way we do it now, all managed servers in a cluster (which is what we configure Prometheus to discover) use the same credentials.
