### ISSUE TITLE
make the exported metrics self-explained 

### ISSUE THREAD

**Issue by lilyhe123** [oracle/weblogic-monitoring-exporter#27]
It's better to have help string in the metrics as described in Prometheus doc: https://prometheus.io/docs/instrumenting/writing_exporters/#help-strings. And the same goes to TYPE field.
See the example metrics exported by Prometheus server.
```
# HELP prometheus_tsdb_wal_truncations_failed_total Total number of WAL truncations that failed.
# TYPE prometheus_tsdb_wal_truncations_failed_total counter
prometheus_tsdb_wal_truncations_failed_total 0
# HELP prometheus_tsdb_wal_truncations_total Total number of WAL truncations attempted.
# TYPE prometheus_tsdb_wal_truncations_total counter
prometheus_tsdb_wal_truncations_total 1
```

**Comment by russgold** [comment]
I agree that it would be, and I would have implemented it if I had any way to get that information. Are you aware of any REST api that contains the documentation? I think it is all in Java comments.

**Comment by tbarnes-us** [comment]
Java mbean comments are accessible via Java APIs, does that help?

**Comment by tbarnes-us** [comment]
You can ask Tom Moreau if there are REST APIs.

**Comment by moreaut** [comment]
There isn't a REST api to get the descriptions.

There is a REST json schema that has them (along with the details of all of the urls, methods, request/response bodies, query params, ...), but there isn't a REST api to get that schema.  Instead, it gets uploaded to a doc doc website.  I haven't checked in a long time to see whether it's still there.

There is a JMX api to get the descriptions (I know you can use WLST to get mbean infos and drill down into them), but I don't know whether you can use JMX (probably 'no') and, even if you could, how you'd map a REST url to the corresponding mbean info.

All in all, I don't think it's feasible for the exporter to provide these descriptions.

**Comment by russgold** [comment]
Closing as not feasible
