### ISSUE TITLE
wls-exporter logging issue

### ISSUE THREAD

**Issue by krishnabhat1986** [oracle/weblogic-monitoring-exporter#290]
Hello,
We have deployed the wls-exporter.war file from the weblogic console to our deployments and we are able to successfully see the metrics. The concern is the application is logging with the metrics response in JSON format and we need to know how this logging can be disabled. (as there is [huge] logging seen at application end for this)
[dm-server-1.zip](https://github.com/oracle/weblogic-monitoring-exporter/files/11200180/dm-server-1.zip)
[wls-exporter.zip](https://github.com/oracle/weblogic-monitoring-exporter/files/11200198/wls-exporter.zip)

<Apr 11, 2023 11:58:24,665 AM UTC> <Warning> <com.alcatel.hdm.providers.authentication.HdmUserLoginModuleImpl> <BEA-000000> <Login Status : [ Console : /wls-exporter,UserName :  p$ hdm_admin $p , Originating IP :  p$ 192.168.1.13 $p , Status : Success ]> 
wlsMonitExp - target server Management RESTful services hdm-domain-dm-server-1:7100
wlsMonitExp - getMetrics : request={"links":[],"children":{"applicationRuntimes":{"links":[],"fields":["name"],"children":{"componentRuntimes":{"links":[],"fields":["name","type","deploymentState","contextRoot","sourceInfo","openSessionsHighCount","openSessionsCurrentCount","sessionsOpenedTotalCount","sessionCookieMaxAgeSecs","sessionInvalidationIntervalSecs","sessionTimeoutSecs","singleThreadedServletPoolSize","sessionIDLength","servletReloadCheckSecs","jSPPageCheckSecs"],"children":{"servlets":{"links":[]}}}}}}}
wlsMonitExp - getMetrics : jsonResponse={
    "identity": [],
    "stateVal": 2,
    "type": "ServerRuntime",
    "weblogicVersion": "WebLogic Server 12.2.1.4.0",
    "adminServerHost": "hdm-domain-adminserver",
    "restartRequired": false,
    "overallHealthState": {
[dm-server-1.zip](https://github.com/oracle/weblogic-monitoring-exporter/files/11200166/dm-server-1.zip)

        "state": "ok",
        "subsystemName": "ServerRuntime",
        "partitionName": null,
        "symptoms": []
    },

............

**Comment by rjeberhard** [comment]
Hi @krishnabhat1986, the engineer best able to answer your question is off for a holiday and will be back in a few days. We have others looking for the right solution, but we may need to wait for @russgold.

**Comment by krishnabhat1986** [comment]
Thanks for the update.
It will also be helpful if we would know additionally on disabling the logging, is it possible to log this in a single line format instead in separate lines for time being?

**Comment by russgold** [comment]
@krishnabhat1986 AFAIK, the exporter isn't doing any logging. Do you have logging enabled in WebLogic for web apps? If so, the exporter has no way to modify what is logged.

**Comment by russgold** [comment]
No comment in months.
