### ISSUE TITLE
Weblogic domain monitoring

### ISSUE THREAD

**Issue by rj23495** [oracle/weblogic-monitoring-exporter#3]
Is it possible to monitor managed servers on a particular weblogic domain on kubernetes using prometheus and grafana? I have tried wls monitoring exporter and i have got the metrics of that particular managed server on which i deployed wls exporter war file.

**Comment by russgold** [comment]
That's correct; you're supposed to deploy it to all managed servers. Probably the simplest approach is to deploy it in the Docker image.

**Comment by rj23495** [comment]
but suppose if i wish to classify managed servers in domain specific manner and then i want to monitor those domains so what am i supposed to do?
should i edit my grafana template or something else?

**Comment by russgold** [comment]
I suspect that I don't understand your question. What do you mean by "classify managed servers in domain-specific manner"? You can certainly create two docker images and deploy one to one set of servers and the other to another set, but that seems needlessly complex.

Can you describe what problem you're trying to solve?

**Comment by rj23495** [comment]
like for example i have xyz domain and it has n number of managed servers and i want my dashboard to be configured in a way where when i select a domain i can monitor all the managed server instances in that xyz domain 
i have already tried an tested this deployment of war file and i am just trying some new configuration files like for example i need 4 metrics like classloader, garbage collection rate, gc count so how can i make those configuration yaml files?
i saw the naming conventions on weblogic admin server instance like what are the metric naming convention is used but still i am unable to build my own customized configuration file.
if you could help me with that?

**Comment by rj23495** [comment]
is wls exporter capable to collect metrics as far as garbage collection is concerned like whatever jmx exporter does?
because i am looking for metrics like garbage collection rate garbage collection time, classloading, threads used, etc

**Comment by rj23495** [comment]
how the yaml file fro configurations should be written for garbage collection metrics 
like i have written this file 
---
metricsNameSnakeCase: true
queries:
- applicationRuntimes:
    key: name
    keyName: app
    componentRuntimes:
      type: WebAppComponentRuntime
      prefix: webapp_config_
      key: name
      values: [deploymentState, contextRoot, sourceInfo, openSessionsHighCount, openSessionsCurrentCount, sessionsOpenedTotalCount, sessionCookieMaxAgeSecs, sessionInvalidationIntervalSecs, sessionTimeoutSecs, singleThreadedServletPoolSize, sessionIDLength, servletReloadCheckSecs, jSPPageCheckSecs]
      servlets:
        prefix: weblogic_servlet_
        key: servletName
        values: [invocationTotalCount, reloadTotal, executionTimeAverage, poolMaxCapacity, executionTimeTotal, reloadTotalCount, executionTimeHigh, executionTimeLow]
      workManagerRuntimes:
        prefix: workmanager_
        key: applicationName
        values: [pendingRequests, completedRequests, stuckThreadCount]
- JVMRuntime:
    key: name
    prefix: jvm_
    values: [heapFreeCurrent, heapFreePercent, heapSizeCurrent, heapSizeMax, uptime, processCpuLoad]


i want to include gc metrics but under which category does it fall like application runtime or component runtime?

**Comment by indgirl6** [comment]
I have the exact same question as @rj23495 
How can we scrape GC metrics?
Also is there a list of all possible metrics we can scrape?

**Comment by russgold** [comment]
By design, you can configure prometheus to detect new servers coming up, if you are running in kubernetes. https://blogs.oracle.com/weblogicserver/use-prometheus-and-grafana-to-monitor-weblogic-server-on-kubernetes

There is a list at https://docs.oracle.com/cd/E13222_01/wls/docs100/wlsmbeanref/core/index.html

**Comment by rj23495** [comment]
hey guys i have tried this configuration for mbeans like for gc metrics you can find them in jrockitruntime mbean and from there you can add those metrics count like gc time gc rate and all you can refer this doc where i have found this jrockitruntime mbean. [https://docs.oracle.com/cd/E13222_01/wls/docs100/wlsmbeanref/core/index.html]

**Comment by rj23495** [comment]
`apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: default
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'kubernetes-apiservers'

        kubernetes_sd_configs:
        - role: endpoints
        scheme: https

        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: default;kubernetes;https

      - job_name: 'kubernetes-nodes'
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__address__]
            action: replace
            regex: '(.*):10250'
            replacement: '${1}:10255'
            target_label: __address__

      - job_name: 'kubernetes-pods'

        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: pod_name
        - regex: '(controller_revision_hash|job)'
          action: labeldrop
        - source_labels: [name]
          regex: '.*/(.*)$'
          replacement: $1
          target_label: webapp
        basic_auth:
         username: weblogic
         password: weblogic1

      - job_name: 'kubernetes-cadvisor'

        scheme: http

        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        kubernetes_sd_configs:
        - role: node

        relabel_configs:
        - source_labels: [__meta_kubernetes_node_address_InternalIP]
          target_label: __address__
          regex: (.*)
          replacement: $1:4194
      
      - job_name: 'kubernetes-service-endpoints'

        kubernetes_sd_configs:
        - role: endpoints

        relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
          action: replace
          target_label: __scheme__
          regex: (https?)
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name`
I am using this as my config map for displaying data of wls exportter but my prometheus page doesnt show the data related to any metric as shown on their website like webapp_--.

below is deployment file:
`apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      serviceAccountName: prometheus
      containers:
        - name: prometheus
          image: prom/prometheus:v2.1.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-storage-volume
          persistentVolumeClaim:
           claimName: prometheus-pvc

`

**Comment by rj23495** [comment]
hey, can we get response time of a weblogic managed server using wls monitoring exporter and if possible which mbean to refer.
actually  we have weblogic managed servers as pods in a cluster and currently we are trying collecting and parsing access logs using ELK stack. 
If we could use this exporter it would be great.

**Comment by rj23495** [comment]
hey! I am trying to get threadpoolruntime metrics just like jvm and as its access point is server runtime mbean i used same configurations as that of jvm runtime i am attaching a file for reference please help if u can...


`---
metricsNameSnakeCase: true
queries:
- applicationRuntimes:
    key: name
    keyName: app
    componentRuntimes:
      type: WebAppComponentRuntime
      prefix: webapp_config_
      key: name
      values: [deploymentState, contextRoot, sourceInfo, openSessionsHighCount, openSessionsCurrentCount, sessionsOpenedTotalCount, sessionCookieMaxAgeSecs, sessionInvalidationIntervalSecs, sessionTimeoutSecs, singleThreadedServletPoolSize, sessionIDLength, servletReloadCheckSecs, jSPPageCheckSecs]
      servlets:
        prefix: weblogic_servlet_
        key: servletName
        values: [invocationTotalCount, reloadTotal, executionTimeAverage, poolMaxCapacity, executionTimeTotal, reloadTotalCount, executionTimeHigh, executionTimeLow]
    workManagerRuntimes:
      prefix: workmanager_
      key: applicationName
      values: [pendingRequests, completedRequests, stuckThreadCount]
    componentRuntimes:
      type: JDBCOracleDataSourceRuntime
      prefix: jdbc_oracle_
      key: name
      values: [activeConnectionsAverageCount, activeConnectionsCurrentCount, activeConnectionsHighCount, connectionsTotalCount, deploymentState, leakedConnectionCount, waitingForConnectionCurrentCount, waitingForConnectionFailureTotal, waitingForConnectionHighCount, waitingForConnectionSuccessTotal, waitingForConnectionTotal, waitSecondsHighCount]
- JVMRuntime:
    key: name
    prefix: jvm_
    values: [heapFreeCurrent, heapFreePercent, heapSizeCurrent, heapSizeMax, uptime, processCpuLoad]
- threadpoolRuntimes:
    key: name
    prefix: threadpool_
    values: [executeThreadTotalCount, throughput, hoggingThreadCount, standbyThreadCount, executeThreads, executeThreadIdleCount]
`

**Comment by russgold** [comment]
Spelling and capitalization count. That should be:

threadPoolRuntime

not

threadpoolRuntimes.
