### ISSUE TITLE
Error : expected a valid start token, got "\r" ("INVALID") while parsing: "\r"

### ISSUE THREAD

**Issue by kebagb** [oracle/weblogic-monitoring-exporter#316]
We had an integration partner work with us on implementing weblogic exporter into Prometheus, amongst other things.
We went to the trouble of deploying the exporter as a .war file into many of our weblogic domains, but then we had unrelated issues on the Prometheus platform, that took quite some time to resolve and took our attention away from the installation of the weblogic exporter.
The integration partner is no longer with us and we are only now starting to pick up the pieces of that work.

I have tested connection to the endpoint from a browser running directly on the target VM and can see metrics coming from http://localhost:<admin-port>/wls-exporter/metrics

I have tested connection to the endpoint by running 'wget' command from the command line of our prometheus VM and can also see metrics that way.

I believe this proves that the issue is neither network nor credentials.

However, when I create a job as below : 
`  - job_name: weblogicAdmin
    metrics_path: /wls-exporter/metrics
    static_configs:
    - targets: ["**.**.**.**:****"]
      labels:
        weblogic_clusterName: 'main'
        weblogic_domainName: '****'
        weblogic_serverName: 'AdminServer'
    basic_auth:
      username: ******
      password: ************`

The target state shows as "DOWN" and I get the Error message : "expected a valid start token, got "\r" ("INVALID") while parsing: "\r""

Incidentally, Prometheus is running on a Linux VM, but Weblogic is running on a Windows VM.
I believe the wls-exporter.war file is from version 1.3.
Upgrading to a later version is not an easy option for us as it is tied into our application release process, so I would like to get some understanding of the issue before going down that path.

**Comment by russgold** [comment]
In the past, we have had issues with Windows, as its line-endings differ from those used on Unix and MacOS. I fixed the issue some years ago, and had a regression reported several months ago, so I had to fix it again and improve the testing. It should be fixed in the latest release.

**Comment by kebagb** [comment]
@russgold Thanks for the info.  

I will look into upgrading to the latest release when we have the opportunity to do that.
