### ISSUE TITLE
Allow to query weblogic.management.mbeanservers.domainruntime MBean tree instead of ServerRuntime

### ISSUE THREAD

**Issue by brx75** [oracle/weblogic-monitoring-exporter#4]
Hi,
it would be nice to have the option to query DomainRuntime instead of ServerRuntime. This way it would be possible to access all the domain metrics from a single place.

**Comment by russgold** [comment]
Sounds like a worthwhile enhancement. Can you tell me how you would use it?

**Comment by russgold** [comment]
In particular, we are trying to understand how this would work in Prometheus; we generally record metrics by server, and domain metrics don't seem to fit.

**Comment by brx75** [comment]
In this way it's possible to delegate the metric collection to the admin
server. Having the server name as a tag in the metric, it would be possible
to only poll a single server instead of the whole domain

**Comment by russgold** [comment]
So... you are not interested in the domain mbeans themselves? You just want to have the queries go to the admin server instead of the managed servers?

**Comment by LorenKonkus** [comment]
I'd like to better  understand  how this  would be used.

When we were first designing  this, our  primary use cases  centered around users harvesting metrics  from WebLogic Server to  view in tools like Grafana. We had  considered building an aggregating  exporter, but all of the other exporters that we surveyed dealt with were server specific, and it seemed very convoluted to map structured data including server identifier fields to useful Grafana renderings so we abandoned that effort. How do you see using this  structured data? 

While the DomainRuntime is an attractive single point of contact, it does come with a cost.  Under the covers, the admin server services these requests by then creating other requests to each required managed server, waiting for responses, and then formatting a single response that aggregates the requested data. This is optimized, multi-threaded, robust code with support for retries and all, but additional requests are always involved, and a single overloaded, slow,  or unresponsive managed  server can still  impact the overall monitoring  experience. The current server-specific model provides for more efficient, timely, and reliable monitoring in small and medium sized domains and minimizes the impact of failure or overload.

What are you trying to  optimize by interacting to the domain runtime over individual server runtimes?

**Comment by brx75** [comment]
Hi,
sorry for the late response.
My intensions was not to force a change in the exporter architecture nor
underlying concepts. It can be useful, in some cases to be able to use the
AdminServer as a proxy for monitoring.
I agree with you that the most simple and streamlined solution is to
connect to each instance and collect metric directly.
