### ISSUE TITLE
Weblogic not listening on hostname labeled interface

### ISSUE THREAD

**Issue by alkalineocelot** [oracle/weblogic-monitoring-exporter#40]
I have a situation where my Weblogic instance is listening on a dedicated application interface which has a DNS name different to the system host name. 

The code that sets the hostname seems to use InetAddress.getLocalHost().getHostName() which returns "myhost", but my Weblogic listen address is a secondary interface with the DNS name "myhost-app"

Is there a way of configuring a hostname for the REST interface in the exporter? (in addition to the port). 

I suspect my alternative is to create a new network channel on the other interface. I haven't tested this yet and would really like to avoid doing that if possible.

A way of configuring this in the YML file would be really helpful.

**Comment by russgold** [comment]
Interesting; not a Kubernetes deployment, I presume. Are you working with a cluster?

I could certainly add a `restHost` field; I am just concerned that it would wind up causing more problems, as using it would absolutely break sharing a configuration across a cluster, and the availability of it would lead users to use it and then report problems.

I'm going to see if there is some other approach possible before heading down that path. I hate to enable one use case, only to break lots of others.

**Comment by alkalineocelot** [comment]
No, not a Kubernetes deployment. This is a SOA Suite cluster deployed on plain old VMs. I'm unfortunately stuck with someone else's bright ideas regarding network configuration however.

I understand what you are saying about the potential problems. I'm also trying to avoid just hacking my way around the problem at my end. Although I'm struggling to think of a reliable (and simple-ish) way to dynamically identify the correct local endpoint. In my case at least I can live with node specific configuration so I might look at just modifying and rebuilding my local copy of wls-exporter.war to use a `restHost` field.

**Comment by russgold** [comment]
I have an idea; could you try building from branch `localport` and see if that addresses your issue without using the `restPort` field?

**Comment by alkalineocelot** [comment]
Tried the localport version but no luck. 
I've created a network channel on the other interface (the one that matches the hostname) to support the connection to the REST API. Was trying to avoid doing that but I can live with it. Seems to work fine now.
