### ISSUE TITLE
Pass host and port as parameter

### ISSUE THREAD

**Issue by umjsio** [oracle/weblogic-monitoring-exporter#400]
Thanks for the great work.

May I know if is it possible to pass the admin server/managed server's hostname and port as a parameter, so that we can expose all servers' metrics with only one deployment on weblogic?

Thank you.

**Comment by russgold** [comment]
I'm afraid not. The exporter is designed to fetch metrics for each server from that server. I know that we considered getting them all from the admin server originally, and decided that wasn't the best approach. I don't recall the reason.
