### ISSUE TITLE
get1.1.sh contains typo in curl command

### ISSUE THREAD

**Issue by DirkNachbar** [oracle/weblogic-monitoring-exporter#44]
Hi,

the latest release of get1.1.sh contains a typo in the curl command:

Currently: curl -L -O https://github.com/oracle/weblogic-monitoring-exporter/releases/download/v1.1/wls-exporter.war

But it should be like this: curl -L -O https://github.com/oracle/weblogic-monitoring-exporter/releases/download/v1.1.0/wls-exporter.war

The source get1.1.sh is here: https://github.com/oracle/weblogic-monitoring-exporter/releases/download/v1.1.0/get1.1.sh

Cheers

Dirk

**Comment by Andtwo** [comment]
I exec the script，but i couldn't get a .zip file.
[root@test1 ~]# sh get1.1.sh config.yml 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9    0     9    0     0      5      0 --:--:--  0:00:01 --:--:--     5
created /tmp/ci-D4EIwebGtX
/tmp/ci-D4EIwebGtX ~
in temp dir
	zip warning: missing end signature--probably not a zip file (did you
	zip warning: remember to use binary mode when you transferred it?)
	zip warning: (if you are trying to read a damaged archive try -F)

zip error: Zip file structure invalid (/root/wls-exporter.war)
~
[root@test1 ~]# ls
anaconda-ks.cfg  ex40.py    mystuff.py   wls-exporter.war
config.yml       get1.1.sh  mystuff.pyc
[root@test1 ~]# ls /tmp/ci-D4EIwebGtX/config.yml 
/tmp/ci-D4EIwebGtX/config.yml

**Comment by russgold** [comment]
Thanks. Should be renamed and fixed now. We had renamed the release and I forgot to change the file.
