### ISSUE TITLE
Error getting the grafana to start using helm

### ISSUE THREAD

**Issue by wenjian80** [oracle/weblogic-monitoring-exporter#45]
Error getting the grafana to start using helm

bash-4.2# kubectl get pvc -n monitoring
NAME             STATUS   VOLUME          CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc-grafana      Bound    pv-grafana      10Gi       RWX            grafana        2m50s
pvc-prometheus   Bound    pv-prometheus   10Gi       RWX            prometheus     68m

bash-4.2# kubectl get po -n monitoring
NAME                                             READY   STATUS             RESTARTS   AGE
grafana-66869f97f4-rlrc4                         0/1     CrashLoopBackOff   4          2m35s
prometheus-kube-state-metrics-6fc5b8c799-4h58f   1/1     Running            0          69m
prometheus-node-exporter-qpthk                   1/1     Running            0          69m
prometheus-server-6b94f7b7fd-b6fvr               2/2     Running            0          69m

kubectl describe po -n monitoring grafana-66869f97f4-rlrc4
Events:
 Type     Reason     Age                From               Message
 ----     ------     ----               ----               -------
 Normal   Scheduled  30s                default-scheduler  Successfully assigned monitoring/grafana-66869f97f4-rlrc4 to worker
 Normal   Pulled     29s                kubelet, worker    Container image "busybox:1.30" already present on machine
 Normal   Created    29s                kubelet, worker    Created container
 Normal   Started    29s                kubelet, worker    Started container
 Warning  Unhealthy  23s                kubelet, worker    Readiness probe failed: Get http://10.244.1.35:3000/api/health: dial tcp 10.244.1.35:3000: connect: connection refused
 Normal   Pulled     22s (x2 over 28s)  kubelet, worker    Container image "grafana/grafana:6.2.4" already present on machine
 Normal   Created    22s (x2 over 28s)  kubelet, worker    Created container
 Normal   Started    22s (x2 over 28s)  kubelet, worker    Started container
 Warning  BackOff    8s (x2 over 16s)   kubelet, worker    Back-off restarting failed container
 
t=2019-06-28T07:46:03+0000 lvl=info msg="Initializing SqlStore" logger=server
t=2019-06-28T07:46:03+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2019-06-28T07:46:03+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2019-06-28T07:46:03+0000 lvl=info msg="Executing migration" logger=migrator id="create migration_log table"
t=2019-06-28T07:46:08+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: database is locked"

kubectl -n monitoring logs -f monitoring grafana-66869f97f4-rlrc4
t=2019-06-28T07:46:03+0000 lvl=info msg="Initializing SqlStore" logger=server
t=2019-06-28T07:46:03+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2019-06-28T07:46:03+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2019-06-28T07:46:03+0000 lvl=info msg="Executing migration" logger=migrator id="create migration_log table"
t=2019-06-28T07:46:08+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: database is locked"

**Comment by lilyhe123** [comment]
As we discussed, first try to change to use NFS PV directly, instead of mounting the NFS folder locally and using HostPath PV.
If still getting the same error, change to use MYSQL instead of Sqlite to workaround it.

Follow the steps below to change to use MySQL for Grafana server:
- Run a MYSQL server following [the step 2 in the end2end sample](https://github.com/oracle/weblogic-monitoring-exporter/blob/master/samples/kubernetes/end2end/docs/02-mysql.md).
- create a database in mysql for grafana

```
kubectl exec -it $POD_NAME -- mysql -p123456 -e "CREATE DATABASE grafana;"
kubectl exec -it $POD_NAME -- mysql -p123456 -e "CREATE USER 'grafana' IDENTIFIED BY 'grafana123';"
kubectl exec -it $POD_NAME -- mysql -p123456 -e "GRANT ALL ON grafana.* TO 'grafana';"
```

- Add following lines to grafana/values.yaml. Then try to install Grafana.
```
grafana.ini:
  database:
    type: mysql
    url: mysql://grafana:grafana123@mysql.default.svc.cluster.local:3306/grafana
```

**Comment by wenjian80** [comment]
Should be an issue with grafana supporting oracle OFS (oracle OCI NFS).
