### ISSUE TITLE
Issue with Configuring Sidecar Deployment for WebLogic using Docker

### ISSUE THREAD

**Issue by Sophisycho** [oracle/weblogic-monitoring-exporter#462]
Hello,

I am currently deploying a sidecar with my WebLogic application. Initially, I attempted to build the project using Maven, but encountered an issue requiring JDK version 21 or higher. However, my WebLogic server is running on JDK 11.

I then switched to using Docker for the deployment, though my WebLogic instance itself is not containerized. Each time I execute the following curl command:

```bash
curl -X PUT -i -u xxxxx:xxxxxx \
    -H "content-type: application/yaml" \
    --data-binary "@/root/node_exporter/DepExporter.yaml" \
    http://xxxxx:8080/configuration
```

I encounter the following error:

```
HTTP/1.1 500 Internal Server Error
Date: Thu, 15 Aug 2024 07:14:30 GMT
Connection: keep-alive
Content-Length: 540

# Unable to contact the REST API at http://172.17.0.2:7001. May be using the wrong host name or port.
#
# This can happen when the exporter is accessed via a load balancer
# configured on a different port than the server's REST API,
# or when the remote server DNS name is not resolvable from the server itself.
#
# You can correct this by giving the exporter WAR an initial configuration with the
# restPort field set to the managed server's plain text port and/or
# restHostName field set to the managed server's locally resolvable name.
```

My YAML configuration already includes the `restHostName` and `restPort` fields, yet I continue to receive a 500 status error. Upon reviewing the error details, I noticed that the IP address being used corresponds to the Docker container's internal IP, and I'm uncertain how to modify this.

When I try to curl `localhost:8080`, I consistently receive the following response:

```
<p>Current Configuration</p>
<p><code><pre>
hostName: 172.17.0.2
port: 7001
queries:
</pre></code></p>
```

I would greatly appreciate your guidance on how to resolve this issue. Thank you for your assistance.

Best regards

**Comment by rjeberhard** [comment]
Hopefully, you will now be able to build with JDK 21 based on the response to the other issue. However, I would also point out that you don't need to build the WAR as it is also available as a resource of each release.

For the question here, is the IP address 172.17.0.2 visible from inside the container that is running the exporter?

**Comment by Sophisycho** [comment]
Hello,

Thank you for your response. I wanted to update you on the issue. I tested accessing the WebLogic REST API both from outside the container and from within the container running the exporter. In both cases, I was able to successfully reach the WebLogic API.

Here are the test results:

**Outside the container:**
```bash
curl -u <username>:<password> http://<domain>:7001/management/weblogic/latest/serverRuntime
```
Response:
```json
{
    "links": [
        {
            "rel": "parent",
            "href": "http://<domain>:7001/management/weblogic/latest"
        },
        {
            "rel": "self",
            "href": "http://<domain>:7001/management/weblogic/latest/serverRuntime"
        },
        {
            "rel": "canonical",
            "href": "http://<domain>:7001/management/weblogic/latest/serverRuntime"
        },
        ...
    ]
}
```

**Inside the container:**
```bash
curl -u <username>:<password> http://<domain>:7001/management/weblogic/latest/serverRuntime
```
Response:
```json
{
    "links": [
        {
            "rel": "parent",
            "href": "http://<domain>:7001/management/weblogic/latest"
        },
        {
            "rel": "self",
            "href": "http://<domain>:7001/management/weblogic/latest/serverRuntime"
        },
        {
            "rel": "canonical",
            "href": "http://<domain>:7001/management/weblogic/latest/serverRuntime"
        },
        ...
    ]
}
```

As you can see, the API is accessible in both environments.

I also wanted to clarify that I am using the sidecar mode, and after checking the release page, I noticed that only the WAR file is available. I'm not sure if the sidecar JAR is also provided in the releases, or if it needs to be built separately.

Thank you again for your assistance.

Best regards.

**Comment by rjeberhard** [comment]
The sidecar is delivered as a container image: `docker pull ghcr.io/oracle/weblogic-monitoring-exporter:2.2.0`

**Comment by Sophisycho** [comment]
Hi

Thanks for your help! I managed to resolve the issue by setting the JAVA_OPTS directly when starting the container with the following command:

bash

```
docker run -d -p 6094:6094 --name wls-exporter -e JAVA_OPTS="-DEXPORTER_PORT=6094 -DWLS_HOST=<My Weblogic Server IP>" ghcr.io/oracle/weblogic-monitoring-exporter:2.2.0
```

This approach worked perfectly.

Best regards.
