### ISSUE TITLE
Inconsistency Between README and Maven Configuration Regarding JDK Version Requirement

### ISSUE THREAD

**Issue by Sophisycho** [oracle/weblogic-monitoring-exporter#463]
Hello,

I have noticed a potential inconsistency regarding the JDK version requirement in the project documentation and the Maven configuration.

In the README, it is stated that building the sidecar implementation requires JDK 11 or later:

```
Note that this requires JDK11 or later; building the project with JDK8 will skip the sidecar module.
```

However, in the Maven configuration file (`pom.xml`), the JDK version requirement is set to 21 or higher:

```xml
<java.version.range>21</java.version.range>
```

This discrepancy could be confusing for users trying to build the project. Could you please confirm whether the project now requires JDK 21, or if the Maven configuration should be adjusted to align with the JDK 11 requirement mentioned in the README?

Thank you for your attention to this matter.

Best regards

**Comment by rjeberhard** [comment]
The build requires JDK 21, but the modules that are part of the WAR deployment are targeted at JDK 8 so that the WAR can be deployed on WebLogic instances running JDK 8 or 11. I'll update the note in the README.

**Comment by Sophisycho** [comment]
Hi @rjeberhard 

Thank you for the clarification on the JDK requirements and for your commitment to updating the README. Your explanation was very helpful.

Best regards
