### ISSUE TITLE
The config.yml can't be reload

### ISSUE THREAD

**Issue by Andtwo** [oracle/weblogic-monitoring-exporter#48]
After i restar weblogic,  i found my monitor data is disable. in order to solve the problem, i have to upload the config.yml again. It doesn't make sense! Would you like to help me?

**Comment by russgold** [comment]
How do I duplicate this problem? How did you set up the exporter? How did you define your config.yml?

**Comment by mriccell** [comment]
Closing this issue due to lack of feedback.  Filer has not responded in 2 weeks.  If Andtwo  or anyone else feels like this issue is still relevant to them, please respond here so that we can reopen this case.
