### ISSUE TITLE
EndToEnd example does not support newest version of prometheus chart

### ISSUE THREAD

**Issue by marinakog** [oracle/weblogic-monitoring-exporter#53]
It was the update on July28 for newest version of the chart for prometheus 8.15.0 .The values.yaml must be update to support it or it will fail to create prometheus-server with error: 
prometheus-server-5bc5568444-nhh9w               1/2     CrashLoopBackOff   11      

log:
level=error ts=2019-07-31T21:56:12.418Z caller=main.go:731 err="opening storage failed: lock DB directory: open /data/lock: permission denied"

version 8.14.3 is tested. For now the best approach to run helm install --wait --name prometheus --namespace monitoring --values  prometheus/values.yaml stable/prometheus --version=8.14.3

**Comment by lilyhe123** [comment]
I can install prometheus 8.15.0 successfully without any change in my environment.
The error you got might be caused by not properly shutting down the server in last run. Can you double check? @marinakog

**Comment by marinakog** [comment]
Hi @lilyhe123 I was constantly getting Jenkins failures since they upgraded to 8.15.0.
For another day I was able successfully run it locally until hit same issue and after that could not make it pass anymore. I could easily reproduce it on my local machine what if switch to 8.14.3 it works and using 8.15.0 does not. My environment is clean. If you check values.yaml from prometheus chart they have added some security to be able to run as nobody  stable/prometheus: run as nobody (#12175). I wonder if we need to check our provided endtoend for prometheus chart values.yaml to add it too

**Comment by lilyhe123** [comment]
Hi @marinakog it turns out my env didn't clean. Now I can reproduce the error. Thank you.
