### ISSUE TITLE
Monitoring Exporter produces combined metrics page with failure, this breaks Prometheus parsing

### ISSUE THREAD

**Issue by marinakog** [oracle/weblogic-monitoring-exporter#54]
If some of the metrics is unavailable, for example JSMServer is failed to start exporter still publishes it to metrics page with this msg:{
 "links": [],
 "fields": [],
 "children": {
   "JMSRuntime": {
     "links": [],
     "children": {
       "JMSServers": {
         "links": [],
         "children": {
           "destinations": {
             "links": []
           }
         }
       }
     }
   }
 }
}
webapp_config_deployment_state{app="bea_wls_cluster_internal",name="managed-server2_/bea_wls_cluster_internal"} 2
webapp_config_deployment_state{app="bea_wls_deployment_internal",name="managed-server2_/bea_wls_deployment_internal"} 2
webapp_config_deployment_state{app="bea_wls_internal",name="managed-server2_/bea_wls_internal"} 2
webapp_config_deployment_state{app="testwsapp",name="managed-server2_/TestWsApp"} 2
webapp_config_deployment_state{app="weblogic",name="managed-server2_/weblogic"} 2
webapp_config_deployment_state{app="wls-exporter",name="managed-server2_/wls-exporter"} 2
webapp_config_deployment_state{app="wls-management-services",name="managed-server2_/management"} 2
webapp_config_open_sessions_current_count{app="bea_wls_cluster_internal",name="managed-server2_/bea_wls_cluster_internal"} 0
webapp_config_open_sessions_current_count{app="bea_wls_deployment_internal",name="managed-server2_/bea_wls_deployment_internal"} 0
webapp_config_open_sessions_current_count{app="bea_wls_internal",name="managed-server2_/bea_wls_internal"} 0
webapp_config_open_sessions_current_count{app="testwsapp",name="managed-server2_/TestWsApp"} 0
webapp_config_open_sessions_current_count{app="weblogic",name="managed-server2_/weblogic"} 0

Mixed metrics info is sent to Prometheus and Prometheus failed to process it for wls targets:
evel=warn ts=2019-07-31T15:42:19.327396722Z caller=scrape.go:835 component="scrape manager" scrape_pool=wls-domain1 target=http://10.244.0.26:8001/wls-exporter/metrics msg="append failed" err="strconv.ParseFloat: parsing \"service\": invalid syntax"
level=warn ts=2019-07-31T15:43:01.190246208Z caller=scrape.go:835 component="scrape manager" scrape_pool=wls-domain1 target=http://10.244.2.32:8001/wls-exporter/metrics msg="append failed" err="strconv.ParseFloat: parsing \"service\": invalid syntax"
Monitoring Exporter should filter failures and send only valid metrics

To reproduce: run end to end example with no database created. It will make JMS server failed to start

**Comment by russgold** [comment]
Fixed by change 9719176d8aea84c1f6c6f9
