### ISSUE TITLE
End2End sample should use download rather than full rebuild

### ISSUE THREAD

**Issue by russgold** [oracle/weblogic-monitoring-exporter#57]
The current instructions in the end2end sample tell the user to build the exporter from source; however, we currently release versions of the exporter, so this should not be necessary. See "Building and Configuring" in the README.

**Comment by lilyhe123** [comment]
Hi Russ, where is the getXXX.sh script? I cannot find it. @russgold

**Comment by russgold** [comment]
If you go to ["releases"](https://github.com/oracle/weblogic-monitoring-exporter/releases) on the project, you will see the latest release. It contains a download link for the appropriate release.
