### ISSUE TITLE
401 Error Every Other Request

### ISSUE THREAD

**Issue by MrRothstein** [oracle/weblogic-monitoring-exporter#63]
We have a domain with 3 clusters ( one server per cluster for now). The exporter is targeted to all servers. When a request to the metrics endpoint is submitted to any host, every second request results in 401 (Authentication Required) error. However, every other request is successful. This is even the case for the AdminServer that is not part of any cluster. One successful request, followed by a failure. The problem goes away when the session cookie header is removed from the request to the REST endpoint.

**Comment by parwezk** [comment]
Hi, What does your prometheus.yml looks like ? how are you passing authentication to weblogic rest api ? and what are the metrics files like jvm.yml or workmanager.yml looks like ?

**Comment by MrRothstein** [comment]
I believe this is an issue with my modified ssl version... I don't think it's handling the secured cookies properly. I'm sorry for the confusion.
