### ISSUE TITLE
prometheus not able to export metrices from wls-exporter

### ISSUE THREAD

**Issue by parwezk** [oracle/weblogic-monitoring-exporter#64]
Hi, prometheus server gives 401 error for wls-exporter end point. That is the target page of prometheus server gives 401 authorization issue with following end point. 
http://host:8001/wls-exporter/metrics, the prometheus.yml looks like following:
 - job_name: 'weblogic' 
metrics_path: '/wls-exporter/metrics' 
static_configs: - targets: ['xxx:8001'], 
and the  configuration at http://host:8001/wls-exporter/ is as follows:
host: slc14ujw.us.oracle.com
port: 8001
query_sync:
  url: http://coordinator:8999/
  refreshInterval: 5
metricsNameSnakeCase: true
restPort: 8001
queries:
- key: name
  keyName: server
  threadPoolRuntime:
    key: name
    keyName: app
    values: throughput

What is the way forward to resolve this issue ? Also, if check the configuration with promtool, I get new line error like below:

 curl http://host:8001/wls-exporter/metrics |./promtool check metrics
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    23  100    23    0     0   1213      0 --:--:-- --:--:-- --:--:--  1277
error while linting: text format parsing error in line 1: unexpected end of input stream

Request you to please help on this.

**Comment by russgold** [comment]
Are you specifying a username/password in your prometheus configuration? The metrics are secured and cannot be accessed without credentials.

**Comment by parwezk** [comment]
Thanks a lot Russel for reply. I actually tried configuring proemtheus.yml like below:

- job_name: 'wls-exporter'
    metrics_path: '/wls-exporter/metrics'
    static_configs:
    - targets: ['slc14ujw.us.oracle.com:8001']
    basic_auth:
     username: 'weblogic'
     password: 'welcome1'

but it gives error like "strconv.ParseFloat: parsing "base_domain": invalid syntax". Request you to please help me on this.

**Comment by russgold** [comment]
Where do you see that error happening? In Prometheus or the exporter?

**Comment by parwezk** [comment]
Thanks Russel for you help, it was infact a issue with deployment, I built the war file from source code and it worked fine.
