### ISSUE TITLE
Scrapping metrices on Admin and managed servers

### ISSUE THREAD

**Issue by parwezk** [oracle/weblogic-monitoring-exporter#65]
Hi, I have a setup where I have one Admin on port 8001and 2 managed servers. I deployed wls-exporter on Admin and cluster (cluster consists of managed-1:9001 and managed-2:9002). Following is my exporter.yml

host: slc14ujw.us.oracle.com
port: 8001
query_sync:
  url: http://coordinator:8999/
  refreshInterval: 5
metricsNameSnakeCase: true
restPort: 8001
queries:
- prefix: wls_server_
  key: name
  keyName: location
  applicationRuntimes:
    key: name
    keyName: app
    componentRuntimes:
      type: WebAppComponentRuntime
      prefix: wls_webapp_config_
      key: name
      values: [deployment_state, deploymentState, contextRoot, sourceInfo, sessionsOpenedTotalCount, openSessionsCurrentCount, openSessionsHighCount]    

The issue is that I do not have load balancer or frontend host for these servers. How do I scrape metrices from managed server as well ? is it possible to configure rest port for managed servers as well ?
P.S: I am successfully able to get metrices from Adminserver:8001

**Comment by russgold** [comment]
The exporter is designed to be deployed on the managed servers. You can use Prometheus to pull data from multiple managed servers, and when you configure it properly, it will even notice when new managed servers have started or old ones shut down.

See https://github.com/oracle/weblogic-monitoring-exporter/tree/master/samples/kubernetes/deployments

**Comment by parwezk** [comment]
Hi Russel, Thnaks a lot for the help, I went through the link and could see that the configurations mentioed are mostly for prometheus and kuberentes. 
My issue is actually like, in want of any LB port which can act as rest port(assuming that LB port can act as restport and can scrap metrices from all servers behind LB port, please request you to correct my understanding if am wrong here), how do we provide configurations to wls-exporter before we deploy it all servers Admin+Managed ones. I use following command to export wls-exporter and build it like : **get1.1.0.sh exporter.yml**, where exporter.yml is as defined above. How do I tell wls-exporter to scrap metices from all servers, because in all examples/samples I found only configuration which uses only one port as rest port. Can I write something like : 
host: slc14ujw.us.oracle.com
port: 8001
query_sync:
url: http://coordinator:8999/
refreshInterval: 5
metricsNameSnakeCase: true
restPort: 8001, 9001, 9002
queries:
prefix: wls_server_
key: name
keyName: location
applicationRuntimes:
key: name
keyName: app
componentRuntimes:
type: WebAppComponentRuntime
prefix: wls_webapp_config_
key: name
values: [deployment_state, deploymentState, contextRoot, sourceInfo, sessionsOpenedTotalCount, openSessionsCurrentCount, openSessionsHighCount]

OR something like:

host: slc14ujw.us.oracle.com
port: 8001
query_sync:
url: http://coordinator:8999/
refreshInterval: 5
metricsNameSnakeCase: true
restPort: 8001
queries:

host: slc14ujw.us.oracle.com
port: 9001
query_sync:
url: http://coordinator:8999/
refreshInterval: 5
metricsNameSnakeCase: true
restPort: 8001
queries:
 etc. 
Many thanks for your response and very eagerly waiting your guidance on this post as well.

**Comment by russgold** [comment]
Yes, the tool was designed explicitly for kubernetes and prometheus; that is its primary use case. You can use prometheus without kubernetes; pretty much everything will work other than managed server discovery.

When you use that command to create the exporter WAR, you are inserting the configuration into it - and that will the configuration on all servers to which it is deployed. If you include the configuration coordinator, and actually run the coordinator, you can change the configuration in one server using the web API and the configuration in all the others will change to match. 

But all must use the same single REST port, and if you are not using Prometheus with Kubernetes, you'll have to have a process that queries each of the managed servers.

**Comment by parwezk** [comment]
Thanks a lot Russel for your guidance. I will explore further on this.
