### ISSUE TITLE
JDBCDataSourceRuntime

### ISSUE THREAD

**Issue by siuwwong55** [oracle/weblogic-monitoring-exporter#66]
Can we export the weblogic JDBCDataSourceRuntime metrics via this wls-exporter? what is the syntax?

**Comment by parwezk** [comment]
Yes you can export metrics, define something like below in your config file.
- JDBCServiceRuntime:
    JDBCDataSourceRuntimeMBeans:
      prefix: wls_datasource_
      key: name
      values: []

**Comment by siuwwong55** [comment]
Thanks a lot!
how can we know the prefix is wls_datasource_ but not jdbc_ or other? is there a way that we can find it out by ourselves?

**Comment by NidaRe** [comment]
Hi,
Could you guide on exact Mbean that can be used to fetch Datasource metrics
https://docs.oracle.com/middleware/1221/wls/WLRUR/toc.htm

Need to use this information for Prometheus monitoring tool.
Thanks,

**Comment by russgold** [comment]
In the documentation, you will find the statement:

"The query field is more complex. Each query consists of a hierarchy of the MBeans, starting relative to ServerRuntimes. Within each section, there are a number of options"

Note that "MBeans" is a link to... the mbeans documentation: https://docs.oracle.com/middleware/1221/wls/WLMBR/core/index.html

You want the runtime mbeans.

**Comment by NidaRe** [comment]
Thanks, I can see lots of attributes under JDBCDataSourceRuntimeMBean

**Comment by siuwwong55** [comment]
yes. I can find the mbeans in the oracle document. but I am not sure how to locate the prefix in the document.

**Comment by russgold** [comment]
The prefix can be anything you like; it is simply a way for you to identify the generated metrics, as different metrics can have the same names.
