### ISSUE TITLE
Can this monitor WebLogic domains which are not in Kubernetes Cluster

### ISSUE THREAD

**Issue by vnandina** [oracle/weblogic-monitoring-exporter#69]
Hi,

I would like to know if this can monitor weblogic domains which are deployed in conventional model and no kubernetes cluster.

Your response is highly appreciated.

Thanks,

**Comment by russgold** [comment]
Absolutely. There may be some use cases which are not supported, but it was originally developed and tested outside a kubernetes cluster.

**Comment by vnandina** [comment]
Thanks for the response. Could you guide me setting this up without kubernetes cluster(like steps to exclude or add) and also is this applicable only for WebLogic 12c or later? We have all 10.3.6 in our environment.

Thanks,

**Comment by russgold** [comment]
It is only for 12.2.1 or later, as it relies on features added in that release; that limitation has nothing to do with kubernetes.

**Comment by jadhep** [comment]
Hi @russgold - i have weblogic 12.2.1 installed on my environment but not in Kubenetes cluster. May i know the step how to use it? Is there any docs that i can referred? 

Thanks.

**Comment by rjeberhard** [comment]
You can follow the steps associated with our Kubernetes operator: https://oracle.github.io/weblogic-kubernetes-operator/userguide/introduction/introduction/

**Comment by mriccell** [comment]
Julian 

Do you have Prometheus?  The monitoring exporter is a web app deployed to the WebLogic cluster and which exported runtime metrics to Prometheus.  Please look at the README in https://github.com/oracle/weblogic-monitoring-exporter.

Monica
