### ISSUE TITLE
How to get values from the landing page of REST API for ServerRuntime 

### ISSUE THREAD

**Issue by sakthiraam** [oracle/weblogic-monitoring-exporter#70]
Hi Team,
I'm trying out the weblogic exporter and i need help in getting the information
1) How to get the values that are available in the landing page of serverRuntime Mbean using the exporter for example openSocketCurrentCount

2) How to access the state value available under the HealthState.

URL --> https://IP:Port/management/weblogic/12.2.1.3.0/serverRuntime/

![image](https://user-images.githubusercontent.com/38710792/68661500-023c2f80-0576-11ea-856f-496aa2ef9f92.png)

Thank You
Regards

**Comment by russgold** [comment]
1.

```
queries:
- values: [openSocketsCurrentCount]
```

2.
HealthState has no numerical values. The exporter is only intended for numerical values.

**Comment by sakthiraam** [comment]
> ```
> queries:
> - values: [openSocketsCurrentCount]
> ```
> 
> 
> HealthState has no numerical values. The exporter is only intended for numerical values.

@russgold , Thanks for your reply. Managed to find the answer in one of the closed case "https://github.com/oracle/weblogic-monitoring-exporter/issues/5" and for the non numerical support will watch the issue opened "https://github.com/oracle/weblogic-monitoring-exporter/issues/62"
