### ISSUE TITLE
CPU data on wls-exporter

### ISSUE THREAD

**Issue by sharonhac** [oracle/weblogic-monitoring-exporter#74]
Hi , is there a way to export the CPU related metrics , such as CPU load via the wls-exporter ? 
using Weblogic 12.2.1.2 and all other metrics appear correctly in the corresponding Grafana Weblogic dashboard which is designated for the metrics exposed by the wls-exporter .. all besides the CPU load .. 

Thanks

**Comment by russgold** [comment]
Can you find mbeans that report that CPU load? The exporter does have a few CPU-related metrics that it always exports.
