### ISSUE TITLE
In Readme.md it is mentioned as "Prometheus and Kibana"

### ISSUE THREAD

**Issue by sbattagi** [oracle/weblogic-monitoring-exporter#79]
In the README.md, it is mentioned as "Prometheus and Kibana". I think it is "Prometheus and Grafana". Please review.

**Comment by russgold** [comment]
I don't see that in the current files. Is it still there?

**Comment by ddsharpe** [comment]
I checked the history on that file.  It has always said "Prometheus and Grafana".  Kibana doesn't appear in the history, anywhere.  @sbattagi Was there a different file or project where you saw this?

**Comment by sbattagi** [comment]
This is the path of the file: samples/kubernetes/deployments/README.md
Looks like this issue has been fixed by the below commit:
https://github.com/oracle/weblogic-monitoring-exporter/commit/80e71e3e39a8b95a784607a8e4436cc7c8de1453
