### ISSUE TITLE
wls-exporter/metrics giving me Not authorized error

### ISSUE THREAD

**Issue by gshreshtha** [oracle/weblogic-monitoring-exporter#80]
I have deployed wls-exporter on a weblogic 12c domain and when I try to access weblogic metrics I get Not authorized error.

url: http://weblogic_host_name:port/wls-exporter/metrics

**Comment by marinakog** [comment]
You need to provide wls user name/password to access the metrics

**Comment by pascalBrand** [comment]
Hello,
After the deployment, I'm trying to check the wls_export metrics with a curl request passing the username and password. It works sometimes and fails with the error "Authentication required.

curl --noproxy "*" --insecure -u monitor:***** https://wsadmin-0.ws1:8443/wls-exporter/metrics

if the curl is run 10 times, it fails almost 6 or 7 times.

Any idea what the issue is ?

Thanks

**Comment by marinakog** [comment]
could you please try to use http and see if it makes difference ( your url shows https). Also what is the version of WLS?

**Comment by pascalBrand** [comment]
Hello Marina,

I deployed the wls-exporter.war 1.1.2 on WebLogic 12.2.1.3 with latest PSU. It seems in http the issue does not reproduce. Do you have a version supporting https ?  

Thanks

**Comment by russgold** [comment]
After you try it and get failures, could you try to access the metrics page directly in your browser, using http? It will be at https://<application-path>/metrics. Then also look at http://<application-path>/messages (note, not "https") and let me know what it shows.

**Comment by gshreshtha** [comment]
Hi,

My curl command with user and password also returns http 500 error. Any idea what is the issue?

curl --noproxy "*" --insecure -u weblogic:********** http://hostname:7100/wls-exporter/metrics
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Draft//EN">
<HTML>
<HEAD>
<TITLE>Error 500--Internal Server Error</TITLE>
</HEAD>
<BODY bgcolor="white">
<FONT FACE=Helvetica><BR CLEAR=all>
<TABLE border=0 cellspacing=5><TR><TD><BR CLEAR=all>
<FONT FACE="Helvetica" COLOR="black" SIZE="3"><H2>Error 500--Internal Server Error</H2>
</FONT></TD></TR>
</TABLE>
<TABLE border=0 width=100% cellpadding=10><TR><TD VALIGN=top WIDTH=100% BGCOLOR=white><FONT FACE="Courier New"><FONT FACE="Helvetica" SIZE="3"><H3>From RFC 2068 <i>Hypertext Transfer Protocol -- HTTP/1.1</i>:</H3>
</FONT><FONT FACE="Helvetica" SIZE="3"><H4>10.5.1 500 Internal Server Error</H4>
</FONT><P><FONT FACE="Courier New">The server encountered an unexpected condition which prevented it from fulfilling the request.</FONT></P>
</FONT></TD></TR>

Thanks,
Shreshtha

**Comment by BSKitman** [comment]
> You need to provide wls user name/password to access the metrics

Hi Thanks,

Can we disable the wls username/password only for accessing the metrics.
Coz, we have multiple customers to monitor, so it will be tough to maintain all those credentials in Prometheus configuration.

**Comment by marinakog** [comment]
the url you mentioned (http://hostname:7100/wls-exporter/metrics) is direct access to wls-exporter app running on WLS server,  only authorized user can access it ( any WLS valid user with credentials).

**Comment by russgold** [comment]
It's an Oracle requirement that all data on a running WebLogic Server instance be password protected. It's not something that is fixable by the developers.

**Comment by mriccell** [comment]
Closing this issue due to lack of feedback.  Filer has not responded in 2 weeks.  If BSKitman or anyone else feels like this issue is still relevant to them, please respond here so that we can reopen this case.
