### ISSUE TITLE
wls_jvm_uptime 

### ISSUE THREAD

**Issue by senthil13** [oracle/weblogic-monitoring-exporter#84]
Weblogic exporter is not exporting all metrics for wls_jvm_uptime.  I am using the basic configuration from 'weblogic-monitoring-exporter/samples/kubernetes/end2end/dashboard/exporter-config.yaml'

wls_jvm_uptime{name="managedServer_2"} 1500822632 

wls_jvm_uptime{domain="domain-1",name="ManagedServer_2"} 2565362660

Where is the issue ?

**Comment by BoLB23** [comment]
I am facing the same issue. some wls_jvm_uptime is showing domain name and managed server name, others are just showing managed server name.

**Comment by marinakog** [comment]
please use 1.1.2 of wls-exporter, also make sure your config yaml for exporter has 

domainQualifier: true

 | If true, the domain name will be included as a qualifier for all metrics. Defaults to false.
-- | --

**Comment by senthil13** [comment]
This can be closed as i am getting consistent value after the 1.1.2 upgrade.
