### ISSUE TITLE
how to support weblogic 10.3.6?

### ISSUE THREAD

**Issue by wanghaiqing2015** [oracle/weblogic-monitoring-exporter#87]
wls-exporter.war 

http://132.232.33.112:7001/wls-exporter/

 
The server has not found anything matching the Request-URI. No indication is given of whether the condition is temporary or permanent.

**Comment by markxnelson** [comment]
WebLogic Monitoring Exporter does not support 10.3.6, the implementation depends on features that were added in WebLogic 12c

**Comment by wanghaiqing2015** [comment]
What can we do?

**Comment by markxnelson** [comment]
We do not intend to make this work with any release before 12c.

**Comment by russgold** [comment]
For earlier versions, you can use the JMX exporter https://github.com/prometheus/jmx_exporter

It will do much the same thing, only more slowly and with more complex configuration.
