### ISSUE TITLE
Query Custom MBean Domain

### ISSUE THREAD

**Issue by cfazzini** [oracle/weblogic-monitoring-exporter#92]
I have some metrics I'd like to scrape that are under a custom mbean domain. In wlst I can access the metrics by first doing "domainCustom()". Is it possible to query these metrics with this exporter?

Thanks

**Comment by marinakog** [comment]
CustomMbeans are not exposed via rest api, so there is no way to query them via monitoring exporter

**Comment by cfazzini** [comment]
Thanks for the info. Back to jmx exporter then. :)
