### ISSUE TITLE
Deployed exporter does not show "REST Services" component 

### ISSUE THREAD

**Issue by adiithyan** [oracle/weblogic-monitoring-exporter#93]
The title might be misleading as I am not sure where the exact problem is, hence apologies in advance :)

Following is the sequence of events;
1. Downloaded source and built the war file using mvn install and mvn package.
2. Added config.yaml to wls-exporter.war(Contents of the config file mentioned towards the end)
3. Deployed wls-exporter from admin console to admin server.
4. The deployed app was listening at the default listen address of the admin server. 
5. Tried to test the app in the testing section (http://hostname:port/wls-exporter) --> 403 Error. 
6. On further inspection through the blogs associated with  weblogic, I understood that there need to be two components inside the deployed app--> "REST Services"  and "Web Services". However, in my scenario, I see only "Web Services" . Is this a problem? 
7. In the event, number 6  is not a problem,  the deployed app is not listening at default address http://hostname:port/wls-exporter. I have tried with localhost, hostname, IP but no luck. Does not look like a DNS resolution issue as other deployed endpoints of apps are accessible through hostname, IP. 
8. For now, I am not trying to access the URL through a load balancer or OHS, hence I have not provided a REST PORT in my config.yaml. 

Note : I am trying this in an on-premise environment.  Config.yaml content mentioned below.

`metricsNameSnakeCase: true
domainQualifier: false
queries:
- key: name
  keyName: location
  prefix: wls_server_
  applicationRuntimes:
    key: name
    keyName: app
    componentRuntimes:
      prefix: wls_webapp_config_
      type: WebAppComponentRuntime
      key: name
      values: [deploymentState, contextRoot, sourceInfo, sessionsOpenedTotalCount, openSessionsCurrentCount, openSessionsHighCount]
      servlets:
        prefix: wls_servlet_
        key: servletName
- JVMRuntime:
    prefix: wls_jvm_
    key: name
- executeQueueRuntimes:
    prefix: wls_socketmuxer_
    key: name
    values: [pendingRequestCurrentCount]
- workManagerRuntimes:
    prefix: wls_workmanager_
    key: name
    values: [stuckThreadCount, pendingRequests, completedRequests]
- threadPoolRuntime:
    prefix: wls_threadpool_
    key: name
    values: [executeThreadTotalCount, queueLength, stuckThreadCount, hoggingThreadCount]
- JMSRuntime:
    key: name
    keyName: jmsruntime
    prefix: wls_jmsruntime_
    JMSServers:
      prefix: wls_jms_
      key: name
      keyName: jmsserver
      destinations:
        prefix: wls_jms_dest_
        key: name
        keyName: destination

- persistentStoreRuntimes:
    prefix: wls_persistentstore_
    key: name
- JDBCServiceRuntime:
    JDBCDataSourceRuntimeMBeans:
      prefix: wls_datasource_
      key: name
- JTARuntime:
    prefix: wls_jta_
    key: name`

**Comment by marinakog** [comment]
wls-exporter should behave as regular web app, please access your admin console and check : 
1. If app was deployed and started and targeted to admin
2. check the context of app is wls-exporter ( you provided it during deployment )
3. if stand alone wls env ( not Kubernetes env) you should use same url as you use to access the console.  If you setup load balancer you need to provide restPort: **** value in the configuration yaml and after redeployment use it's front end port number to access exporter webapp

**Comment by adiithyan** [comment]
App was indeed, deployed and targeted to admin with the corret context (wls-exporter). I am using the same URL that I use to access the console. 
My access logs indicate a 302 redirect first and then a 403 to the end point /wls-exporter. 

What am I missing here?

**Comment by marinakog** [comment]
what version of WLS do you use?

**Comment by marinakog** [comment]
also if you can send server logs. Are you able to access regular webapp? please make sure you use latest version of wls-exporter ( 1.1.2)

**Comment by adiithyan** [comment]
Weblogic version 12.2. 
Exporter : 1.1.2
Regular web applications are accessible. 

My domain (consisting of a few clusters) is an internal domain(i.e not accessible by the internet). The internal domain is accessible because of entries in /etc/hosts. ie the domain name resolves into an accessible ip address/hostname.  Default listen address of the deployed exporter is the domain name. I went through the source code and it looks like localhost is the default host configured. 
 
Could this be a problem?

**Comment by adiithyan** [comment]
Weblogic version 10.3.6
Exporter : 1.1.2
Regular web applications are accessible. 

My domain (consisting of a few clusters) is an internal domain(i.e not accessible by the internet). The internal domain is accessible because of entries in /etc/hosts. ie the domain name resolves into an accessible ip address/hostname.  Default listen address of the deployed exporter is the domain name. I went through the source code and it looks like localhost is the default host configured. 
 
Could this be a problem?

**Comment by rjeberhard** [comment]
Yes, the RESTful management interface was added to WebLogic in version 12.2.1.0.

**Comment by adiithyan** [comment]
Thank you. My bad that I did not notice the version requirements clearly.
