### ISSUE TITLE
HealthState metrics 

### ISSUE THREAD

**Issue by ankitakhot92** [oracle/weblogic-monitoring-exporter#94]
can we get 'healthState' related metrics from weblogic monitoring exporter for workmanager and jta? what is the syntax ?

**Comment by lennyphan** [comment]
Should be able to get health metrics for workmanager and JTA.  Will investigate the query/syntax and post.

**Comment by mriccell** [comment]
JTA health state is an interface https://docs.oracle.com/middleware/11119/wls/WLAPI/weblogic/health/HealthState.html not sure that the monitoring exporter can handle interfaces. @russgold ?

**Comment by mriccell** [comment]
HealthState is under JTARuntimeMBean, but is not an mbean itself. The REST api doesn't support it.  We have entered an enhancement request so that JTA runtime MBeans be exposed via  REST APIS for Transaction Monitoring.  
Thanks
Monica

**Comment by lennyphan** [comment]
The same issue for HealthState for WorkManager since it's the same object class.
