### ISSUE TITLE
how to get Metrics for attributes like ActiveSessionCount, ActiveSubSessionCount 

### ISSUE THREAD

**Issue by taelagab** [oracle/weblogic-monitoring-exporter#97]
Hi,
I want to get metrics related to attributes like ActiveSessionCount, ActiveSubSessionCount etc. I found the closest match JMSConnectionRuntimeMBean which has SessionsCurrentCount Attribute.

I mentioned the following in config but I'm not able to scrape any.

  - JMSConnectionRuntime:
      prefix: jms_session_
      key: name
      values: [SessionsCurrentCount,SessionsHighCount,SessionsTotalCount]

**Comment by russgold** [comment]
Are you specifically looking for _JMS connection_ sessions?
