### ISSUE TITLE
StatisticsRuntimeMBean

### ISSUE THREAD

**Issue by ankitakhot92** [oracle/weblogic-monitoring-exporter#99]
How can we assess StatisticsRuntimeMBean ? What is its syntax ? I have tried this
  -  StatisticsRuntimeMBean:
        prefix: wls_statistics_
        key: name

But doesn't generate any metrics. And also doesn't give out any error.

**Comment by ankitakhot92** [comment]
https://docs.oracle.com/cd/E69505_01/doc.72/e69506/opg_statistics.htm#WSEAD1133 

Can we retrieve metrics like SESSION_COUNT, SESSION_PEAK, SUB_SESSION_COUNT and others mentioned in above link through wls-monitoring-exporter. In the link its mentioned to use StatisticsRuntimeMBean. 

What must be the Mbean Hierarchy for StatisticsRuntimeMbean ?

**Comment by russgold** [comment]
Look at the title of the page:

Communications WebRTC Session Controller System Administrator's Guide

The exporter can show information from WebLogic Server. You seem to be looking at the guide for a completely different product, with which I am unfamiliar.
